#!/bin/sh

if ! [ $(id -u) = 0 ]; then
   echo "This script must be run as root" 
   exit 1
fi

if [ "$1" != "-i" ]; then
  echo "Unsupported parameter for fake dpkg. Only simple version 'dpkg -i package.deb' will work."
  exit 1
fi

PACKAGE=$2
CURDIR=`pwd`

echo Installing $PACKAGE

mkdir -p /tmp/dpkg/data
#mkdir -p /tmp/dpkg/control
cd /tmp/dpkg

ar x $CURDIR/$PACKAGE
tar xzf data.tar.* -C data
#tar xzf control.tar.* -C control

#if [ -x /tmp/dpkg/control/preinst ]; then
# /tmp/dpkg/control/preinst
#fi

cp -rp /tmp/dpkg/data/* /

#if [ -x /tmp/dpkg/control/postinst ]; then
# /tmp/dpkg/control/postinst
#fi

rm -R /tmp/dpkg
